### ISSUE TITLE
Erro de intervalo 28 dias ao invés de 7 dias

### ISSUE THREAD

**Issue by rodrigodrds** [TeoMeWhy/ds-bricks#12]
https://github.com/TeoMeWhy/ds-bricks/blob/b2b7e2b3f936054d477af9101070dd13ba74e730/src/feature_store/fs_pontos.sql#L21

Vendo a gravação esse dado ficou errado no PR

**Comment by TeoCalvo** [comment]
Muito obrigado, correção realizada em #13
